{{- if and .Values.createUserJob.serviceAccount.create .Values.webserver.defaultUser.enabled }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.createUserJob.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "createUserJob.serviceAccountName" . }}
  labels:
    tier: faststack
    component: create-user-job
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- if or (.Values.labels) (.Values.createUserJob.labels) }}
      {{- mustMerge .Values.createUserJob.labels .Values.labels | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.createUserJob.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
