{{- if and .Values.pgbouncer.enabled .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "faststack.fullname" . }}-pgbouncer-policy
  labels:
    tier: faststack
    component: faststack-pgbouncer-policy
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      tier: faststack
      component: pgbouncer
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: faststack
          release: {{ .Release.Name }}
    {{- if .Values.pgbouncer.extraNetworkPolicies}}
      {{- toYaml .Values.pgbouncer.extraNetworkPolicies | nindent 4 }}
    {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.ports.pgbouncer }}
    - protocol: TCP
      port: {{ .Values.ports.pgbouncerScrape }}
{{- end }}
