{{- if and (not .Values.logs.persistence.existingClaim ) .Values.logs.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "faststack_logs_volume_claim" . }}
  labels:
    tier: faststack
    component: logs-pvc
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.logs.persistence.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: {{ .Values.logs.persistence.size | quote }}
  {{- if .Values.logs.persistence.storageClassName }}
  {{- if (eq "-" .Values.logs.persistence.storageClassName) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ tpl .Values.logs.persistence.storageClassName . | quote }}
  {{- end }}
  {{- end }}
{{- end }}
