{{- if (and .Values.pgbouncer.enabled (not .Values.pgbouncer.configSecretName)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgbouncer_config_secret" . }}
  labels:
    tier: faststack
    component: pgbouncer
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  pgbouncer.ini: {{ include "pgbouncer_config" . | b64enc }}
  users.txt: {{ include "pgbouncer_users" . | b64enc }}
{{- end }}
