{{- if or .Values.pgbouncer.ssl.ca .Values.pgbouncer.ssl.cert .Values.pgbouncer.ssl.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgbouncer_certificates_secret" . }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- if .Values.pgbouncer.ssl.ca }}
  root.crt: {{ .Values.pgbouncer.ssl.ca | b64enc }}
  {{- end }}
  {{- if .Values.pgbouncer.ssl.cert }}
  server.crt: {{ .Values.pgbouncer.ssl.cert | b64enc }}
  {{- end }}
  {{- if .Values.pgbouncer.ssl.key }}
  server.key: {{ .Values.pgbouncer.ssl.key | b64enc }}
  {{- end }}
{{- end }}
