apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "faststack_config" . }}
  labels:
    tier: faststack
    component: config
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end -}}
  {{- if .Values.faststackConfigAnnotations }}
  annotations: {{- toYaml .Values.faststackConfigAnnotations | nindent 4 }}
  {{- end }}
{{- $Global := . }}
data:
  faststack.cfg: |-
    {{- range $section, $settings := .Values.config }}
    [{{ $section }}]
    {{- range $key, $val := $settings }}
    {{ $key }} = {{ tpl ($val | toString) $Global }}
    {{- end }}
    {{ end }}