{{- if .Values.webserver.enabled }}
{{- if .Values.webserver.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "faststack.fullname" . }}-webserver-pdb
  labels:
    tier: faststack
    component: webserver
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    {{- if or (.Values.labels) (.Values.webserver.labels) }}
      {{- mustMerge .Values.webserver.labels .Values.labels | toYaml | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      tier: faststack
      component: webserver
      release: {{ .Release.Name }}
  {{- toYaml .Values.webserver.podDisruptionBudget.config | nindent 2 }}
{{- end }}
{{- end }}
