{{- if .Values.webserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "faststack.fullname" . }}-webserver
  labels:
    tier: faststack
    component: webserver
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- if or (.Values.labels) (.Values.webserver.labels) }}
      {{- mustMerge .Values.webserver.labels .Values.labels | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.webserver.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webserver.service.type }}
  selector:
    tier: faststack
    component: webserver
    release: {{ .Release.Name }}
  ports:
  {{ range .Values.webserver.service.ports }}
    -
      {{- range $key, $val := . }}
      {{ $key }}: {{ tpl (toString $val) $ }}
      {{- end }}
  {{- end }}
  {{- if .Values.webserver.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.webserver.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.webserver.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.webserver.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
{{- end }}
