{{- if and .Values.webserver.enabled .Values.webserver.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.webserver.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "webserver.serviceAccountName" . }}
  labels:
    tier: faststack
    component: webserver
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- if or (.Values.labels) (.Values.webserver.labels) }}
      {{- mustMerge .Values.webserver.labels .Values.labels | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.webserver.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
